ALTER TABLE hubs
    ADD COLUMN IF NOT EXISTS monthly_fee DOUBLE PRECISION NOT NULL DEFAULT 299.00,
    ADD COLUMN IF NOT EXISTS auto_renew BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS payment_method_id VARCHAR(100);
